version: 2.1
# orbs:
#   version: 2.1
#   description: Orb for firebase deploy.
#   commands:
#     deploy:
#       description: Deploy to firebase
#       parameters:
#         token:
#           type: string
#           description: Firebase Deploy Token
#       steps:
#         - run:
#             name: Install Firebase Tools
#             command: npm install --prefix=./firebase-deploy firebase-tools
#         - run:
#             name: Deploy to Firebase
#             command: ./firebase-deploy/node_modules/.bin/firebase deploy --token=<< parameters.token >>

jobs:
  test:
    docker:
      - image: circleci/node:12.7.0
    steps:
      - checkout
      - run: npm run test
