version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.7.0-stretch-browsers
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Test
          command: npm run test
